// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsospiecqhztzfhoogkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzb3NwaWVjcWh6dHpmaG9vZ2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMDM5NjcsImV4cCI6MjA3MzU3OTk2N30.ligqM0HyVpx2RYDAtY9cO8c1yZ6HkTtIW_hNFucuTI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});