// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxjlbhywsqrwhwscsayr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4amxiaHl3c3Fyd2h3c2NzYXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjg3MjUsImV4cCI6MjA3MzcwNDcyNX0.Vw-dgWiEAhC-vHbg04YiX-i4xBSb75BrBLAu6cfe7Q0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});